[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install --immutable --immutable-cache"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "npx medusa db:migrate && yarn start"
